/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author NITRO 5
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form tampilanadmin
     */
    public admin() {
        initComponents();
    }
    public admin(String Username){
        initComponents();
        jLabel1.setText(Username);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonTiket = new javax.swing.JButton();
        jButtonJadwalTayang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU ADMIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 270, 60);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jButtonTiket.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButtonTiket.setText("TIKET");
        jButtonTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTiketMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonTiket);
        jButtonTiket.setBounds(80, 200, 140, 60);

        jButtonJadwalTayang.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButtonJadwalTayang.setText("JADWAL TAYANG");
        jButtonJadwalTayang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJadwalTayangMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonJadwalTayang);
        jButtonJadwalTayang.setBounds(340, 200, 220, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTiketMouseClicked
        tiket t = new tiket();
    }//GEN-LAST:event_jButtonTiketMouseClicked

    private void jButtonJadwalTayangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJadwalTayangMouseClicked
        jadwaltayang j = new jadwaltayang();
    }//GEN-LAST:event_jButtonJadwalTayangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJadwalTayang;
    private javax.swing.JButton jButtonTiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
    
